version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    image: books-python-image
    container_name: books-app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: bash -c
      "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - rabitmq
    restart: on-failure # always
    environment:
      - DEBUG=${DEBUG}
      - C_BROKER=${CELERY_BROKER}
      - C_BACKEND=${CELERY_BACKEND}
      - E_BACKEND=${EMAIL_BACKEND}
      - E_HOST=${EMAIL_HOST}
      - E_USE_TLS=${EMAIL_USE_TLS}
      - E_USE_SSL=${EMAIL_USE_SSL}
      - E_PORT=${EMAIL_POR}
      - E_HOST_USER=${EMAIL_HOST_USER}
      - E_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}

  celery:
    image: books-python-image
    container_name: books-celery
    command: celery -A app worker -P prefork -c 2 -l info
    volumes:
      - ./app:/app
    depends_on:
      - rabitmq
    restart: on-failure
    environment:
      - DEBUG=${DEBUG}
      - C_BROKER=${CELERY_BROKER}
      - C_BACKEND=${CELERY_BACKEND}
      - E_BACKEND=${EMAIL_BACKEND}
      - E_HOST=${EMAIL_HOST}
      - E_USE_TLS=${EMAIL_USE_TLS}
      - E_USE_SSL=${EMAIL_USE_SSL}
      - E_PORT=${EMAIL_POR}
      - E_HOST_USER=${EMAIL_HOST_USER}
      - E_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}

  rabitmq:
    image: rabbitmq:3-management
    container_name: books-rabbitmq
    ports:
    - '15672:15672'
    - '5672:5672'
    restart: on-failure